openapi: 3.0.3
info:
  title: Sample API
  description: A sample API demonstration
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  $ref: './paths/paths.yml'

components:
  schemas:
    $ref: './components/schemas.yml'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 